package com.smarttrust.common.exception;

/**
 * Enterprise error codes — stable, machine-readable, frontend can map to messages.
 */
public enum ErrorCode {
    // Auth
    AUTH_INVALID_CREDENTIALS,
    AUTH_PHONE_ALREADY_EXISTS,
    AUTH_OTP_EXPIRED,
    AUTH_OTP_INVALID,
    AUTH_OTP_MAX_ATTEMPTS,
    AUTH_OTP_NOT_FOUND,
    AUTH_ACCOUNT_LOCKED,
    AUTH_ACCOUNT_NOT_ACTIVE,
    AUTH_ACCOUNT_SUSPENDED,
    AUTH_ACCOUNT_BANNED,
    AUTH_PHONE_NOT_VERIFIED,
    AUTH_REFRESH_TOKEN_INVALID,
    AUTH_REFRESH_TOKEN_EXPIRED,
    AUTH_REFRESH_TOKEN_REVOKED,
    AUTH_TOO_MANY_REQUESTS,
    AUTH_EMAIL_ALREADY_EXISTS,
    AUTH_OTP_RESEND_COOLDOWN,
    AUTH_EMAIL_NOT_VERIFIED,
    AUTH_ROLE_REQUIRED,
    AUTH_ROLE_ALREADY_SELECTED,

    // Validation & Common
    VALIDATION_FAILED,
    RESOURCE_NOT_FOUND,
    CONFLICT,
    FORBIDDEN,
    UNAUTHORIZED,
    RATE_LIMIT_EXCEEDED,

    // Customer / Provider / Categories / Documents
    CUSTOMER_PROFILE_NOT_FOUND,
    PROVIDER_PROFILE_NOT_FOUND,
    PROVIDER_DOCS_REQUIRED,
    PROVIDER_INVALID_STATUS_TRANSITION,
    CATEGORY_NOT_FOUND,
    CATEGORY_ALREADY_EXISTS,
    DOCUMENT_INVALID_TYPE,
    FILE_TOO_LARGE,
    FILE_STORAGE_ERROR,
    DOCUMENT_NOT_FOUND,

    // System
    INTERNAL_ERROR
}
